[package]
name = "formater-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ffs"
path = "src/main.rs"

[dependencies]
ignore = "0.4"
anyhow = "1.0.103"
tempfile = "3.27.0"
walkdir = "2.5.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
 
[dev-dependencies]
tempfile = "=3.27.0"
 
[profile.release]
opt-level = 3
lto = true
